@host = https://localhost:7137
@ownerName = me

### Create Wishlist Collection
POST {{host}}/WishlistCollection
Content-Type: application/json

{
    "owner": "me"
}

### Get Collection for owner
GET {{host}}/WishlistCollection/{{ownerName}}

### Create Wishlist
POST {{host}}/WishlistCollection/{{ownerName}}/wishlist
Content-Type: application/json

{
    "name": "My Wishlist"
}

### Get Collection for owner
# @name GetWishlists
GET {{host}}/WishlistCollection/{{ownerName}}

### Set WishlistId
@wishlistId = {{GetWishlists.response.body.$[0].id}}

### Get Wishlist
GET {{host}}/WishlistCollection/{{ownerName}}/wishlist/29ffae41-13c2-4189-b7cb-563e83743f7a

