@local=https://localhost:7137
@remote=https://itsybitsylist-api.azurewebsites.net
@host = {{remote}}

@ownerName = me
### Create Wishlist
# @name CreateWishlist
POST {{host}}/wishlist
Content-Type: application/json

{
    "name": "My first wishlist"
}
###
@location = {{CreateWishlist.response.headers.Location}}
### Retrieve Wishlist
Get {{location}}
owner: {{ownerName}}

### Get Collection for owner
# @name GetWishlists
GET {{host}}/wishlist
owner: {{ownerName}}

### Set WishlistId
@wishlistId = {{GetWishlists.response.body.$[0].id}}

### Get Wishlist
GET {{host}}/wishlist/{{wishlistId}}
owner: {{ownerName}}